-- VHDL Entity ece411.ClrHByte.generatedInstance
--
-- Created:
--          by - schen79.ews (linux-a2.ews.illinois.edu)
--          at - 16:00:24 09/12/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ClrHByte IS
   PORT( 
      clk         : IN     std_logic;
      ClrHByteout : OUT    LC3b_word;
      RFMuxout    : IN     LC3b_word
   );

END ClrHByte ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ClrHByte IS 
BEGIN


END generatedInstance;
