-- VHDL Entity ece411.Datapath.interface
--
-- Created:
--          by - chao16.ews (gelib-057-36.ews.illinois.edu)
--          at - 20:03:27 11/17/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Datapath IS
   PORT( 
      D_DATAIN    : IN     LC3B_WORD;
      D_MRESP_H   : IN     STD_LOGIC;
      I_DATAIN    : IN     LC3B_WORD;
      I_MRESP_H   : IN     STD_LOGIC;
      RESET_L     : IN     STD_LOGIC;
      Start_H     : IN     std_logic;
      clk         : IN     STD_LOGIC;
      D_ADDRESS   : OUT    LC3b_word;
      D_DATAOUT   : OUT    LC3b_word;
      D_MREAD_L   : OUT    std_logic;
      D_MWRITEH_L : OUT    std_logic;
      D_MWRITEL_L : OUT    std_logic;
      I_ADDRESS   : OUT    LC3B_WORD;
      I_MREAD_L   : OUT    std_logic
   );

-- Declarations

END Datapath ;

--
-- VHDL Architecture ece411.Datapath.struct
--
-- Created:
--          by - chao16.ews (gelib-057-36.ews.illinois.edu)
--          at - 20:03:28 11/17/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;
USE ieee.std_logic_arith.all;

LIBRARY mp3lib;

ARCHITECTURE struct OF Datapath IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL A2                : STD_LOGIC;
   SIGNAL ADDR1Muxsel1      : std_logic;
   SIGNAL ADDR2Muxsel1      : LC3B_4MUX_SEL;
   SIGNAL ALUMuxsel1        : LC3B_4MUX_SEL;
   SIGNAL ALUop1            : LC3B_ALUOP;
   SIGNAL B                 : STD_LOGIC;
   SIGNAL BR_Opcode         : std_logic;
   SIGNAL CONTROL           : CONTROL_WORD;
   SIGNAL CheckN            : std_logic;
   SIGNAL CheckP            : std_logic;
   SIGNAL CheckZ            : std_logic;
   SIGNAL DRMuxsel1         : std_logic;
   SIGNAL EX_ADJ8out        : LC3b_word;
   SIGNAL EX_ALU            : LC3b_word;
   SIGNAL EX_ALUOUT         : LC3b_word;
   SIGNAL EX_BRAdd          : LC3b_word;
   SIGNAL EX_BRAddout       : LC3b_word;
   SIGNAL EX_CONTROL_OUT    : CONTROL_WORD;
   SIGNAL EX_Opcode         : LC3b_opcode;
   SIGNAL EX_PCPlus2        : LC3b_word;
   SIGNAL EX_RFA            : LC3b_word;
   SIGNAL EX_dest           : LC3b_reg;
   SIGNAL F                 : STD_LOGIC;
   SIGNAL F1                : STD_LOGIC;
   SIGNAL F10               : STD_LOGIC;
   SIGNAL F11               : STD_LOGIC;
   SIGNAL F12               : STD_LOGIC;
   SIGNAL F13               : STD_LOGIC;
   SIGNAL F14               : STD_LOGIC;
   SIGNAL F15               : STD_LOGIC;
   SIGNAL F16               : STD_LOGIC;
   SIGNAL F17               : STD_LOGIC;
   SIGNAL F2                : STD_LOGIC;
   SIGNAL F3                : STD_LOGIC;
   SIGNAL F4                : STD_LOGIC;
   SIGNAL F5                : STD_LOGIC;
   SIGNAL F6                : STD_LOGIC;
   SIGNAL F7                : STD_LOGIC;
   SIGNAL F8                : STD_LOGIC;
   SIGNAL F9                : STD_LOGIC;
   SIGNAL GenCCMuxsel1      : std_logic;
   SIGNAL ID_ADJ11out       : LC3b_word;
   SIGNAL ID_ADJ6out        : LC3b_word;
   SIGNAL ID_ADJ8out        : LC3b_word;
   SIGNAL ID_ADJ9out        : LC3b_word;
   SIGNAL ID_CONTROL_OUT    : CONTROL_WORD;
   SIGNAL ID_IMM5out        : LC3b_word;
   SIGNAL ID_Opcode         : LC3b_opcode;
   SIGNAL ID_PCPlus2        : LC3b_word;
   SIGNAL ID_RFA            : LC3b_word;
   SIGNAL ID_RFAout         : LC3b_word;
   SIGNAL ID_RFB            : LC3b_word;
   SIGNAL ID_RFBout         : LC3b_word;
   SIGNAL ID_SEXT6out       : LC3b_word;
   SIGNAL ID_dest           : LC3b_reg;
   SIGNAL IF_ADJ11out       : LC3b_word;
   SIGNAL IF_ADJ6out        : LC3b_word;
   SIGNAL IF_ADJ8out        : LC3b_word;
   SIGNAL IF_ADJ9out        : LC3b_word;
   SIGNAL IF_CONTROL_OUT    : CONTROL_WORD;
   SIGNAL IF_IMM5           : LC3B_IMM5;
   SIGNAL IF_IMM5out        : LC3b_word;
   SIGNAL IF_INDEX6         : LC3B_INDEX6;
   SIGNAL IF_IR             : LC3b_word;
   SIGNAL IF_IR11           : std_logic;
   SIGNAL IF_IR11out        : std_logic;
   SIGNAL IF_IR4out         : std_logic;
   SIGNAL IF_IR5            : std_logic;
   SIGNAL IF_IR5out         : std_logic;
   SIGNAL IF_IRout          : LC3b_word;
   SIGNAL IF_OFFSET11       : LC3B_OFFSET11;
   SIGNAL IF_OFFSET9        : LC3B_OFFSET9;
   SIGNAL IF_Opcode         : LC3b_opcode;
   SIGNAL IF_PCPlus2        : LC3b_word;
   SIGNAL IF_PCPlus2out     : LC3b_word;
   SIGNAL IF_SEXT6out       : LC3b_word;
   SIGNAL IF_SrcA           : LC3b_reg;
   SIGNAL IF_SrcB           : LC3b_reg;
   SIGNAL IF_TRAPVECT8      : LC3b_TRAPVECT8;
   SIGNAL IF_dest           : LC3b_reg;
   SIGNAL IF_opcodeout      : LC3b_opcode;
   SIGNAL Load              : std_logic;
   SIGNAL Load2             : std_logic;
   SIGNAL LoadNZP1          : std_logic;
   SIGNAL LoadPC            : STD_LOGIC;
   SIGNAL LoadPC2           : STD_LOGIC;
   SIGNAL MARMuxsel         : LC3B_4MUX_SEL;
   SIGNAL MDRMuxsel         : LC3B_4MUX_SEL;
   SIGNAL MEM_ALU           : LC3b_word;
   SIGNAL MEM_BRAdd         : LC3b_word;
   SIGNAL MEM_CONTROL_OUT   : CONTROL_WORD;
   SIGNAL MEM_MARout        : LC3b_word;
   SIGNAL MEM_MDR           : LC3b_word;
   SIGNAL MEM_MDRout        : LC3b_word;
   SIGNAL MEM_Opcode        : LC3b_opcode;
   SIGNAL MEM_PCPlus2       : LC3b_word;
   SIGNAL MEM_dest          : LC3b_reg;
   SIGNAL MREAD_L           : std_logic;
   SIGNAL MWRITE_L          : std_logic;
   SIGNAL PCMuxsel          : LC3b_4Mux_sel;
   SIGNAL RFMux2sel1        : LC3B_4MUX_SEL;
   SIGNAL RFMuxsel1         : LC3B_4MUX_SEL;
   SIGNAL Read_H            : std_logic;
   SIGNAL RegWrite1         : std_logic;
   SIGNAL StoreMuxsel1      : std_logic;
   SIGNAL WB_RFMuxout       : LC3b_word;
   SIGNAL WB_WriteRegisters : std_logic;
   SIGNAL Write_H           : std_logic;
   SIGNAL n                 : std_logic;
   SIGNAL p                 : std_logic;
   SIGNAL preI_MREAD_L      : std_logic;
   SIGNAL preLoad2          : std_logic;
   SIGNAL preLoadPC         : STD_LOGIC;
   SIGNAL takeBr            : std_logic;
   SIGNAL test              : STD_LOGIC;
   SIGNAL z                 : std_logic;


   -- Component Declarations
   COMPONENT ADJ_SEXT_Unit
   PORT (
      IF_IMM5      : IN     LC3b_imm5 ;
      IF_INDEX6    : IN     LC3b_index6 ;
      IF_OFFSET11  : IN     LC3b_offset11 ;
      IF_OFFSET9   : IN     LC3b_offset9 ;
      IF_TRAPVECT8 : IN     LC3b_trapvect8 ;
      clk          : IN     std_logic ;
      IF_ADJ11out  : OUT    LC3b_word ;
      IF_ADJ6out   : OUT    LC3b_word ;
      IF_ADJ8out   : OUT    LC3b_word ;
      IF_ADJ9out   : OUT    LC3b_word ;
      IF_IMM5out   : OUT    LC3b_word ;
      IF_SEXT6out  : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT COMP4
   PORT (
      A        : IN     LC3b_opcode;
      BROpcode : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT Control_ROM
   PORT (
      IR      : IN     LC3b_word;
      IR11    : IN     std_logic;
      IR4     : IN     std_logic;
      IR5     : IN     std_logic;
      clk     : IN     std_logic;
      opcode  : IN     LC3b_OPCODE;
      start_h : IN     std_logic;
      takeBr  : IN     std_logic;
      CONTROL : OUT    CONTROL_WORD
   );
   END COMPONENT;
   COMPONENT Reg_EX_MEM
   PORT (
      EX_ALUout      : IN     LC3b_word;
      EX_BRAddout    : IN     LC3b_word;
      EX_CONTROL_IN  : IN     CONTROL_WORD;
      ID_ADJ8out     : IN     LC3b_word;
      ID_Opcode      : IN     LC3b_opcode;
      ID_PCPlus2     : IN     LC3b_word;
      ID_RFB         : IN     LC3b_word;
      ID_dest        : IN     LC3b_reg;
      Load           : IN     std_logic;
      Reset_L        : IN     std_logic;
      clk            : IN     std_logic;
      EX_ADJ8out     : OUT    LC3b_word;
      EX_ALU         : OUT    LC3b_word;
      EX_BRAdd       : OUT    LC3b_word;
      EX_CONTROL_OUT : OUT    CONTROL_WORD;
      EX_Opcode      : OUT    LC3b_opcode;
      EX_PCPlus2     : OUT    LC3b_word;
      EX_RFB         : OUT    LC3b_word;
      EX_dest        : OUT    LC3b_reg
   );
   END COMPONENT;
   COMPONENT Reg_ID_EX
   PORT (
      ID_CONTROL_IN  : IN     CONTROL_WORD;
      ID_RFAout      : IN     LC3b_word;
      ID_RFBout      : IN     LC3b_word;
      IF_ADJ11out    : IN     LC3b_word;
      IF_ADJ6out     : IN     LC3b_word;
      IF_ADJ8out     : IN     LC3b_word;
      IF_ADJ9out     : IN     LC3b_word;
      IF_IMM5out     : IN     LC3b_word;
      IF_IR11        : IN     std_logic;
      IF_IR5         : IN     std_logic;
      IF_Opcode      : IN     LC3b_opcode;
      IF_PCPlus2     : IN     LC3b_word;
      IF_SEXT6out    : IN     LC3b_word;
      IF_dest        : IN     LC3b_reg;
      Load           : IN     std_logic;
      Reset_L        : IN     std_logic;
      clk            : IN     std_logic;
      ID_ADJ11out    : OUT    LC3b_word;
      ID_ADJ6out     : OUT    LC3b_word;
      ID_ADJ8out     : OUT    LC3b_word;
      ID_ADJ9out     : OUT    LC3b_word;
      ID_CONTROL_OUT : OUT    CONTROL_WORD;
      ID_IMM5out     : OUT    LC3b_word;
      ID_IR11        : OUT    std_logic;
      ID_IR5         : OUT    std_logic;
      ID_Opcode      : OUT    LC3b_opcode;
      ID_PCPlus2     : OUT    LC3b_word;
      ID_RFA         : OUT    LC3b_word;
      ID_RFB         : OUT    LC3b_word;
      ID_SEXT6out    : OUT    LC3b_word;
      ID_dest        : OUT    LC3b_reg
   );
   END COMPONENT;
   COMPONENT Reg_IF_ID
   PORT (
      IF_CONTROL_IN  : IN     CONTROL_WORD;
      IF_IR_IN       : IN     LC3b_word;
      IF_PCPlus2out  : IN     LC3b_word;
      Load           : IN     std_logic;
      Reset_L        : IN     std_logic;
      clk            : IN     std_logic;
      IF_CONTROL_OUT : OUT    CONTROL_WORD;
      IF_IMM5        : OUT    LC3B_IMM5;
      IF_INDEX6      : OUT    LC3B_INDEX6;
      IF_IR          : OUT    LC3b_word;
      IF_IR11        : OUT    std_logic;
      IF_IR5         : OUT    std_logic;
      IF_OFFSET11    : OUT    LC3B_OFFSET11;
      IF_OFFSET9     : OUT    LC3B_OFFSET9;
      IF_Opcode      : OUT    LC3b_opcode;
      IF_PCPlus2     : OUT    LC3b_word;
      IF_SrcA        : OUT    LC3b_reg;
      IF_SrcB        : OUT    LC3b_reg;
      IF_TRAPVECT8   : OUT    LC3B_TRAPVECT8;
      IF_dest        : OUT    LC3b_reg;
      IF_shftop      : OUT    LC3b_shftop
   );
   END COMPONENT;
   COMPONENT Reg_MEM_WB
   PORT (
      EX_ALU          : IN     LC3b_word;
      EX_BRAdd        : IN     LC3b_word;
      EX_Opcode       : IN     LC3b_opcode;
      EX_PCPlus2      : IN     LC3b_word;
      EX_dest         : IN     LC3b_reg;
      Load            : IN     std_logic;
      MEM_CONTROL_IN  : IN     CONTROL_WORD;
      MEM_MDRout      : IN     LC3b_word;
      Reset_L         : IN     std_logic;
      clk             : IN     std_logic;
      MEM_ALU         : OUT    LC3b_word;
      MEM_BRAdd       : OUT    LC3b_word;
      MEM_CONTROL_OUT : OUT    CONTROL_WORD;
      MEM_MDR         : OUT    LC3b_word;
      MEM_Opcode      : OUT    LC3b_opcode;
      MEM_PCPlus2     : OUT    LC3b_word;
      MEM_dest        : OUT    LC3b_reg
   );
   END COMPONENT;
   COMPONENT Splitter_EX
   PORT (
      CONTROL     : IN     CONTROL_WORD;
      ADDR1Muxsel : OUT    std_logic;
      ADDR2Muxsel : OUT    LC3B_4MUX_SEL;
      ALUMuxsel   : OUT    LC3B_4MUX_SEL;
      ALUop       : OUT    LC3B_ALUOP
   );
   END COMPONENT;
   COMPONENT Splitter_ID
   PORT (
      CONTROL     : IN     CONTROL_WORD;
      DRMuxsel    : OUT    std_logic;
      StoreMuxsel : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT Splitter_IF
   PORT (
      CONTROL  : IN     CONTROL_WORD;
      PCMuxsel : OUT    LC3b_4Mux_sel
   );
   END COMPONENT;
   COMPONENT Splitter_MEM
   PORT (
      CONTROL   : IN     CONTROL_WORD;
      MARMuxsel : OUT    LC3B_4MUX_SEL;
      MDRMuxsel : OUT    LC3B_4MUX_SEL;
      PCMuxsel  : OUT    LC3B_4MUX_SEL;
      Read_H    : OUT    std_logic;
      Write_H   : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT Splitter_WB
   PORT (
      CONTROL     : IN     CONTROL_WORD;
      GenCCMuxsel : OUT    std_logic;
      LoadNZP     : OUT    std_logic;
      RFMux2sel   : OUT    LC3B_4MUX_SEL;
      RFMuxsel    : OUT    LC3B_4MUX_SEL;
      RegWrite    : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT Stage_Execute
   PORT (
      ADDR1Muxsel : IN     std_logic ;
      ADDR2Muxsel : IN     LC3b_4mux_sel ;
      ALUMuxsel   : IN     LC3b_4mux_sel ;
      ALUop       : IN     LC3b_aluop ;
      EX_ADJ11    : IN     LC3b_word ;
      EX_ADJ6     : IN     LC3b_word ;
      EX_ADJ9     : IN     LC3b_word ;
      EX_IMM5     : IN     LC3b_word ;
      EX_PCPlus2  : IN     LC3b_word ;
      EX_RFAout   : IN     LC3b_word ;
      EX_RFBout   : IN     LC3b_word ;
      EX_SEXT6    : IN     LC3b_word ;
      clk         : IN     std_logic ;
      EX_ALUOUT   : OUT    LC3b_word ;
      EX_BRAddout : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT Stage_ID
   PORT (
      DRMuxsel          : IN     std_logic ;
      ID_RegFileIn      : IN     LC3b_word ;
      ID_SrcA           : IN     LC3b_reg ;
      ID_SrcB           : IN     LC3b_reg ;
      ID_dest           : IN     LC3b_reg ;
      IF_dest           : IN     LC3b_reg ;
      RESET_L           : IN     std_logic ;
      StoreMuxsel       : IN     std_logic ;
      WB_WriteRegisters : IN     std_logic ;
      clk               : IN     std_logic ;
      ID_RFAout         : OUT    LC3b_word ;
      ID_RFBout         : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT Stage_IF
   PORT (
      IF_BRAddout   : IN     LC3b_word ;
      IF_MDRout     : IN     LC3b_word ;
      I_DATAIN      : IN     LC3b_word ;
      I_MRESP_H     : IN     std_logic ;
      LoadPC        : IN     std_logic ;
      PCMuxSel      : IN     LC3b_4mux_sel ;
      RESET_L       : IN     std_logic ;
      clk           : IN     std_logic ;
      IF_IR11       : OUT    std_logic ;
      IF_IR4        : OUT    std_logic ;
      IF_IR5        : OUT    std_logic ;
      IF_IRout      : OUT    LC3b_word ;
      IF_PCPlus2out : OUT    LC3b_word ;
      IF_PCout      : OUT    LC3b_word ;
      IF_opcode     : OUT    LC3b_opcode 
   );
   END COMPONENT;
   COMPONENT Stage_Memory
   PORT (
      DATAIN        : IN     LC3b_word ;
      EX_RFB        : IN     LC3b_word ;
      Load          : IN     std_logic ;
      MARMuxsel     : IN     LC3b_4mux_sel ;
      MDRMuxsel     : IN     LC3b_4mux_sel ;
      MEM_ALUout    : IN     LC3b_word ;
      MEM_PCPlus2   : IN     LC3b_word ;
      MEM_TRAPVECT8 : IN     LC3b_word ;
      MRESP_H       : IN     STD_LOGIC ;
      RESET_L       : IN     std_logic ;
      Read_H        : IN     STD_LOGIC ;
      Write_H       : IN     STD_LOGIC ;
      clk           : IN     std_logic ;
      MEM_MARout    : OUT    LC3b_word ;
      MEM_MDRout    : OUT    LC3b_word ;
      MREAD_L       : OUT    std_logic ;
      MWRITE_L      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Stage_WB
   PORT (
      GenCCMuxsel       : IN     std_logic ;
      LoadNZP           : IN     std_logic ;
      RFMux2sel         : IN     LC3b_4mux_sel ;
      RFMuxsel          : IN     LC3b_4mux_sel ;
      RegWrite          : IN     std_logic ;
      WB_ALUout         : IN     LC3b_word ;
      WB_BRAddout       : IN     LC3b_word ;
      WB_MDRout         : IN     LC3b_word ;
      WB_PCPlus2out     : IN     LC3b_word ;
      WB_dest           : IN     LC3b_reg ;
      clk               : IN     std_logic ;
      CheckN            : OUT    std_logic ;
      CheckP            : OUT    std_logic ;
      CheckZ            : OUT    std_logic ;
      WB_RFMuxout       : OUT    LC3b_word ;
      WB_WriteRegisters : OUT    std_logic ;
      n                 : OUT    std_logic ;
      p                 : OUT    std_logic ;
      z                 : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT checkBR
   PORT (
      CheckN    : IN     std_logic ;
      CheckP    : IN     std_logic ;
      CheckZ    : IN     std_logic ;
      n         : IN     std_logic ;
      p         : IN     std_logic ;
      z         : IN     std_logic ;
      BR_Opcode : IN     std_logic ;
      takeBr    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT delay_unit
   PORT (
      clk : IN     STD_LOGIC ;
      A2  : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT delay_unit2
   PORT (
      test     : IN     STD_LOGIC ;
      preLoad2 : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT delay_unit3
   PORT (
      test      : IN     STD_LOGIC ;
      preLoadPC : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT delay_unit4
   PORT (
      preI_MREAD_L : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT AND2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT AND3
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      C : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT NOT1
   PORT (
      A : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;
   COMPONENT OR2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ADJ_SEXT_Unit USE ENTITY ece411.ADJ_SEXT_Unit;
   FOR ALL : AND2 USE ENTITY mp3lib.AND2;
   FOR ALL : AND3 USE ENTITY mp3lib.AND3;
   FOR ALL : COMP4 USE ENTITY ece411.COMP4;
   FOR ALL : Control_ROM USE ENTITY ece411.Control_ROM;
   FOR ALL : NOT1 USE ENTITY mp3lib.NOT1;
   FOR ALL : OR2 USE ENTITY mp3lib.OR2;
   FOR ALL : Reg_EX_MEM USE ENTITY ece411.Reg_EX_MEM;
   FOR ALL : Reg_ID_EX USE ENTITY ece411.Reg_ID_EX;
   FOR ALL : Reg_IF_ID USE ENTITY ece411.Reg_IF_ID;
   FOR ALL : Reg_MEM_WB USE ENTITY ece411.Reg_MEM_WB;
   FOR ALL : Splitter_EX USE ENTITY ece411.Splitter_EX;
   FOR ALL : Splitter_ID USE ENTITY ece411.Splitter_ID;
   FOR ALL : Splitter_IF USE ENTITY ece411.Splitter_IF;
   FOR ALL : Splitter_MEM USE ENTITY ece411.Splitter_MEM;
   FOR ALL : Splitter_WB USE ENTITY ece411.Splitter_WB;
   FOR ALL : Stage_Execute USE ENTITY ece411.Stage_Execute;
   FOR ALL : Stage_ID USE ENTITY ece411.Stage_ID;
   FOR ALL : Stage_IF USE ENTITY ece411.Stage_IF;
   FOR ALL : Stage_Memory USE ENTITY ece411.Stage_Memory;
   FOR ALL : Stage_WB USE ENTITY ece411.Stage_WB;
   FOR ALL : checkBR USE ENTITY ece411.checkBR;
   FOR ALL : delay_unit USE ENTITY ece411.delay_unit;
   FOR ALL : delay_unit2 USE ENTITY ece411.delay_unit2;
   FOR ALL : delay_unit3 USE ENTITY ece411.delay_unit3;
   FOR ALL : delay_unit4 USE ENTITY ece411.delay_unit4;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- DATAOUT = MDRout
   -- DATAOUT <= MEM_MDRout;

   -- HDL Embedded Text Block 2 eb2
   D_ADDRESS <= MEM_MARout;                                

   -- HDL Embedded Text Block 3 eb3
   D_MREAD_L <= MREAD_L;                             

   -- HDL Embedded Text Block 4 eb4
   D_MWRITEH_L <= MWRITE_L;                               

   -- HDL Embedded Text Block 5 eb5
   D_MWRITEL_L <= MWRITE_L;                               

   -- HDL Embedded Text Block 6 eb6
   D_DATAOUT <= MEM_MDRout;                              


   -- Instance port mappings.
   aADJ_SEXT_Unit : ADJ_SEXT_Unit
      PORT MAP (
         IF_IMM5      => IF_IMM5,
         IF_INDEX6    => IF_INDEX6,
         IF_OFFSET11  => IF_OFFSET11,
         IF_OFFSET9   => IF_OFFSET9,
         IF_TRAPVECT8 => IF_TRAPVECT8,
         clk          => clk,
         IF_ADJ11out  => IF_ADJ11out,
         IF_ADJ6out   => IF_ADJ6out,
         IF_ADJ8out   => IF_ADJ8out,
         IF_ADJ9out   => IF_ADJ9out,
         IF_IMM5out   => IF_IMM5out,
         IF_SEXT6out  => IF_SEXT6out
      );
   U_10 : COMP4
      PORT MAP (
         A        => MEM_Opcode,
         BROpcode => BR_Opcode
      );
   aControl_ROM : Control_ROM
      PORT MAP (
         clk     => clk,
         start_h => Start_H,
         opcode  => IF_opcodeout,
         takeBr  => takeBr,
         IR4     => IF_IR4out,
         IR5     => IF_IR5out,
         IR11    => IF_IR11out,
         IR      => IF_IRout,
         CONTROL => CONTROL
      );
   aReg_EX_MEM : Reg_EX_MEM
      PORT MAP (
         clk            => clk,
         Reset_L        => RESET_L,
         Load           => Load,
         EX_ALUout      => EX_ALUOUT,
         EX_BRAddout    => EX_BRAddout,
         ID_Opcode      => ID_Opcode,
         ID_dest        => ID_dest,
         ID_ADJ8out     => ID_ADJ8out,
         ID_PCPlus2     => ID_PCPlus2,
         ID_RFB         => ID_RFB,
         EX_ALU         => EX_ALU,
         EX_BRAdd       => EX_BRAdd,
         EX_Opcode      => EX_Opcode,
         EX_dest        => EX_dest,
         EX_ADJ8out     => EX_ADJ8out,
         EX_PCPlus2     => EX_PCPlus2,
         EX_RFB         => EX_RFA,
         EX_CONTROL_IN  => ID_CONTROL_OUT,
         EX_CONTROL_OUT => EX_CONTROL_OUT
      );
   aREG_ID_EX : Reg_ID_EX
      PORT MAP (
         clk            => clk,
         Reset_L        => RESET_L,
         Load           => Load,
         ID_RFAout      => ID_RFAout,
         ID_RFBout      => ID_RFBout,
         IF_Opcode      => IF_Opcode,
         IF_dest        => IF_dest,
         IF_IR5         => IF_IR5,
         IF_IR11        => IF_IR11,
         IF_ADJ6out     => IF_ADJ6out,
         IF_ADJ8out     => IF_ADJ8out,
         IF_ADJ9out     => IF_ADJ9out,
         IF_ADJ11out    => IF_ADJ11out,
         IF_IMM5out     => IF_IMM5out,
         IF_SEXT6out    => IF_SEXT6out,
         IF_PCPlus2     => IF_PCPlus2,
         ID_RFA         => ID_RFA,
         ID_RFB         => ID_RFB,
         ID_Opcode      => ID_Opcode,
         ID_dest        => ID_dest,
         ID_IR5         => OPEN,
         ID_IR11        => OPEN,
         ID_ADJ6out     => ID_ADJ6out,
         ID_ADJ8out     => ID_ADJ8out,
         ID_ADJ9out     => ID_ADJ9out,
         ID_ADJ11out    => ID_ADJ11out,
         ID_IMM5out     => ID_IMM5out,
         ID_SEXT6out    => ID_SEXT6out,
         ID_PCPlus2     => ID_PCPlus2,
         ID_CONTROL_IN  => IF_CONTROL_OUT,
         ID_CONTROL_OUT => ID_CONTROL_OUT
      );
   aREG_IF_ID : Reg_IF_ID
      PORT MAP (
         clk            => clk,
         Reset_L        => RESET_L,
         Load           => Load,
         IF_IR_IN       => IF_IRout,
         IF_PCPlus2out  => IF_PCPlus2out,
         IF_IR          => IF_IR,
         IF_IMM5        => IF_IMM5,
         IF_INDEX6      => IF_INDEX6,
         IF_TRAPVECT8   => IF_TRAPVECT8,
         IF_OFFSET9     => IF_OFFSET9,
         IF_OFFSET11    => IF_OFFSET11,
         IF_Opcode      => IF_Opcode,
         IF_SrcA        => IF_SrcA,
         IF_SrcB        => IF_SrcB,
         IF_dest        => IF_dest,
         IF_shftop      => OPEN,
         IF_IR5         => IF_IR5,
         IF_IR11        => IF_IR11,
         IF_PCPlus2     => IF_PCPlus2,
         IF_CONTROL_IN  => CONTROL,
         IF_CONTROL_OUT => IF_CONTROL_OUT
      );
   aReg_MEM_WB : Reg_MEM_WB
      PORT MAP (
         clk             => clk,
         Reset_L         => RESET_L,
         Load            => Load,
         EX_ALU          => EX_ALU,
         EX_BRAdd        => EX_BRAdd,
         EX_PCPlus2      => EX_PCPlus2,
         EX_dest         => EX_dest,
         EX_Opcode       => EX_Opcode,
         MEM_MDRout      => MEM_MDRout,
         MEM_ALU         => MEM_ALU,
         MEM_BRAdd       => MEM_BRAdd,
         MEM_PCPlus2     => MEM_PCPlus2,
         MEM_MDR         => MEM_MDR,
         MEM_dest        => MEM_dest,
         MEM_Opcode      => MEM_Opcode,
         MEM_CONTROL_IN  => EX_CONTROL_OUT,
         MEM_CONTROL_OUT => MEM_CONTROL_OUT
      );
   aSplitter_EX : Splitter_EX
      PORT MAP (
         CONTROL     => ID_CONTROL_OUT,
         ADDR1Muxsel => ADDR1Muxsel1,
         ADDR2Muxsel => ADDR2Muxsel1,
         ALUMuxsel   => ALUMuxsel1,
         ALUop       => ALUop1
      );
   aSplitter_ID : Splitter_ID
      PORT MAP (
         CONTROL     => IF_CONTROL_OUT,
         DRMuxsel    => DRMuxsel1,
         StoreMuxsel => StoreMuxsel1
      );
   U_8 : Splitter_IF
      PORT MAP (
         CONTROL  => CONTROL,
         PCMuxsel => PCMuxsel
      );
   aSplitter_MEM : Splitter_MEM
      PORT MAP (
         CONTROL   => EX_CONTROL_OUT,
         MARMuxsel => MARMuxsel,
         MDRMuxsel => MDRMuxsel,
         Read_H    => Read_H,
         Write_H   => Write_H,
         PCMuxsel  => OPEN
      );
   aSplitter_WB : Splitter_WB
      PORT MAP (
         CONTROL     => MEM_CONTROL_OUT,
         GenCCMuxsel => GenCCMuxsel1,
         LoadNZP     => LoadNZP1,
         RFMux2sel   => RFMux2sel1,
         RFMuxsel    => RFMuxsel1,
         RegWrite    => RegWrite1
      );
   aStage_Execute : Stage_Execute
      PORT MAP (
         ADDR1Muxsel => ADDR1Muxsel1,
         ADDR2Muxsel => ADDR2Muxsel1,
         ALUMuxsel   => ALUMuxsel1,
         ALUop       => ALUop1,
         EX_ADJ11    => ID_ADJ11out,
         EX_ADJ6     => ID_ADJ6out,
         EX_ADJ9     => ID_ADJ9out,
         EX_IMM5     => ID_IMM5out,
         EX_PCPlus2  => ID_PCPlus2,
         EX_RFAout   => ID_RFA,
         EX_RFBout   => ID_RFB,
         EX_SEXT6    => ID_SEXT6out,
         clk         => clk,
         EX_ALUOUT   => EX_ALUOUT,
         EX_BRAddout => EX_BRAddout
      );
   aStage_ID : Stage_ID
      PORT MAP (
         DRMuxsel          => DRMuxsel1,
         ID_RegFileIn      => WB_RFMuxout,
         ID_SrcA           => IF_SrcA,
         ID_SrcB           => IF_SrcB,
         ID_dest           => MEM_dest,
         IF_dest           => IF_dest,
         RESET_L           => RESET_L,
         StoreMuxsel       => StoreMuxsel1,
         WB_WriteRegisters => WB_WriteRegisters,
         clk               => clk,
         ID_RFAout         => ID_RFAout,
         ID_RFBout         => ID_RFBout
      );
   aStage_IF : Stage_IF
      PORT MAP (
         IF_BRAddout   => MEM_BRAdd,
         IF_MDRout     => MEM_MDRout,
         I_DATAIN      => I_DATAIN,
         I_MRESP_H     => I_MRESP_H,
         LoadPC        => Load,
         PCMuxSel      => PCMuxsel,
         RESET_L       => RESET_L,
         clk           => clk,
         IF_IR11       => IF_IR11out,
         IF_IR4        => IF_IR4out,
         IF_IR5        => IF_IR5out,
         IF_IRout      => IF_IRout,
         IF_PCPlus2out => IF_PCPlus2out,
         IF_PCout      => I_ADDRESS,
         IF_opcode     => IF_opcodeout
      );
   aStage_Memory : Stage_Memory
      PORT MAP (
         DATAIN        => D_DATAIN,
         EX_RFB        => EX_RFA,
         Load          => Load,
         MARMuxsel     => MARMuxsel,
         MDRMuxsel     => MDRMuxsel,
         MEM_ALUout    => EX_ALU,
         MEM_PCPlus2   => EX_PCPlus2,
         MEM_TRAPVECT8 => EX_ADJ8out,
         MRESP_H       => D_MRESP_H,
         RESET_L       => RESET_L,
         Read_H        => Read_H,
         Write_H       => Write_H,
         clk           => clk,
         MEM_MARout    => MEM_MARout,
         MEM_MDRout    => MEM_MDRout,
         MREAD_L       => MREAD_L,
         MWRITE_L      => MWRITE_L
      );
   aStage_WB : Stage_WB
      PORT MAP (
         GenCCMuxsel       => GenCCMuxsel1,
         LoadNZP           => LoadNZP1,
         RFMux2sel         => RFMux2sel1,
         RFMuxsel          => RFMuxsel1,
         RegWrite          => RegWrite1,
         WB_ALUout         => MEM_ALU,
         WB_BRAddout       => MEM_BRAdd,
         WB_MDRout         => MEM_MDR,
         WB_PCPlus2out     => MEM_PCPlus2,
         WB_dest           => MEM_dest,
         clk               => clk,
         CheckN            => CheckN,
         CheckP            => CheckP,
         CheckZ            => CheckZ,
         WB_RFMuxout       => WB_RFMuxout,
         WB_WriteRegisters => WB_WriteRegisters,
         n                 => n,
         p                 => p,
         z                 => z
      );
   acheckBR : checkBR
      PORT MAP (
         CheckN    => CheckN,
         CheckP    => CheckP,
         CheckZ    => CheckZ,
         n         => n,
         p         => p,
         z         => z,
         BR_Opcode => BR_Opcode,
         takeBr    => takeBr
      );
   U_6 : delay_unit
      PORT MAP (
         clk => clk,
         A2  => A2
      );
   U_3 : delay_unit2
      PORT MAP (
         test     => test,
         preLoad2 => preLoad2
      );
   U_7 : delay_unit3
      PORT MAP (
         test      => test,
         preLoadPC => preLoadPC
      );
   U_11 : delay_unit4
      PORT MAP (
         preI_MREAD_L => preI_MREAD_L
      );
   U_4 : AND2
      PORT MAP (
         A => clk,
         B => B,
         F => test
      );
   U_12 : AND2
      PORT MAP (
         A => F1,
         B => D_MRESP_H,
         F => F8
      );
   U_15 : AND2
      PORT MAP (
         A => F12,
         B => D_MRESP_H,
         F => F3
      );
   U_20 : AND2
      PORT MAP (
         A => F5,
         B => F6,
         F => F7
      );
   U_24 : AND2
      PORT MAP (
         A => F9,
         B => F11,
         F => F10
      );
   U_30 : AND2
      PORT MAP (
         A => F13,
         B => D_MRESP_H,
         F => F16
      );
   U_31 : AND2
      PORT MAP (
         A => F17,
         B => F14,
         F => F15
      );
   U_13 : AND3
      PORT MAP (
         A => F2,
         B => preLoad2,
         C => I_MRESP_H,
         F => Load
      );
   U_16 : AND3
      PORT MAP (
         A => F4,
         B => preLoadPC,
         C => I_MRESP_H,
         F => LoadPC
      );
   U_1 : NOT1
      PORT MAP (
         A => F,
         F => I_MREAD_L
      );
   U_5 : NOT1
      PORT MAP (
         A => A2,
         F => B
      );
   U_18 : NOT1
      PORT MAP (
         A => Read_H,
         F => F5
      );
   U_19 : NOT1
      PORT MAP (
         A => Write_H,
         F => F6
      );
   U_22 : NOT1
      PORT MAP (
         A => Read_H,
         F => F9
      );
   U_23 : NOT1
      PORT MAP (
         A => Write_H,
         F => F11
      );
   U_28 : NOT1
      PORT MAP (
         A => Read_H,
         F => F17
      );
   U_29 : NOT1
      PORT MAP (
         A => Write_H,
         F => F14
      );
   U_9 : OR2
      PORT MAP (
         A => Read_H,
         B => Write_H,
         F => F1
      );
   U_14 : OR2
      PORT MAP (
         A => Read_H,
         B => Write_H,
         F => F12
      );
   U_17 : OR2
      PORT MAP (
         A => Read_H,
         B => Write_H,
         F => F13
      );
   U_21 : OR2
      PORT MAP (
         A => F8,
         B => F7,
         F => F2
      );
   U_25 : OR2
      PORT MAP (
         A => F3,
         B => F10,
         F => F4
      );
   U_26 : OR2
      PORT MAP (
         A => Load,
         B => Start_H,
         F => Load2
      );
   U_27 : OR2
      PORT MAP (
         A => LoadPC,
         B => Start_H,
         F => LoadPC2
      );
   U_32 : OR2
      PORT MAP (
         A => F16,
         B => F15,
         F => F
      );

END struct;
