-- VHDL Entity ece411.Delay.generatedInstance
--
-- Created:
--          by - chng2.ews (linux-a2.ews.illinois.edu)
--          at - 03:19:12 11/01/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Delay IS
   PORT( 
      clk : IN     std_logic
   );

END Delay ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF Delay IS 
BEGIN


END generatedInstance;
