-- VHDL Entity ece411.L1CacheWithWriteEvict.symbol
--
-- Created:
--          by - li151.ews (gelib-057-06.ews.illinois.edu)
--          at - 13:53:53 12/06/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L1CacheWithWriteEvict IS
   PORT( 
      ADDRESS   : IN     LC3b_word;
      DATAOUT   : IN     LC3b_word;
      MREAD_L   : IN     std_logic;
      MWRITEH_L : IN     std_logic;
      MWRITEL_L : IN     std_logic;
      PMDATAIN  : IN     LC3B_OWORD;
      PMRESP_H  : IN     std_logic;
      RESET_L   : IN     std_logic;
      clk       : IN     std_logic;
      DATAIN    : OUT    LC3B_WORD;
      MRESP_H   : OUT    std_logic;
      PMADDRESS : OUT    LC3b_word;
      PMDATAOUT : OUT    LC3B_OWORD;
      PMREAD_L  : OUT    std_logic;
      PMWRITE_L : OUT    std_logic
   );

-- Declarations

END L1CacheWithWriteEvict ;

--
-- VHDL Architecture ece411.L1CacheWithWriteEvict.struct
--
-- Created:
--          by - li151.ews (gelib-057-06.ews.illinois.edu)
--          at - 13:53:53 12/06/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF L1CacheWithWriteEvict IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL DataWriteMuxout : LC3B_OWORD;
   SIGNAL Dirty           : std_logic;
   SIGNAL InLoad          : std_logic;
   SIGNAL InWaitHit       : std_logic;
   SIGNAL InWriteBack     : std_logic;
   SIGNAL Miss            : std_logic;


   -- Component Declarations
   COMPONENT EvictionWriteBuffer
   PORT (
      DataWriteMuxout : IN     LC3B_OWORD ;
      InWriteBack     : IN     std_logic ;
      PMRESP_H        : IN     std_logic ;
      RESET_L         : IN     std_logic ;
      clk             : IN     std_logic ;
      PMDATAOUT       : OUT    LC3B_OWORD ;
      PMWRITE_L       : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT L1WithWriteEvict
   PORT (
      ADDRESS         : IN     LC3b_word ;
      DATAOUT         : IN     LC3b_word ;
      InLoad          : IN     std_logic ;
      InWaitHit       : IN     std_logic ;
      InWriteBack     : IN     std_logic ;
      MREAD_L         : IN     std_logic ;
      MWRITEH_L       : IN     std_logic ;
      MWRITEL_L       : IN     std_logic ;
      PMDATAIN        : IN     LC3B_OWORD ;
      RESET_L         : IN     std_logic ;
      clk             : IN     std_logic ;
      DATAIN          : OUT    LC3B_WORD ;
      DataWriteMuxout : OUT    LC3B_OWORD ;
      Dirty           : OUT    std_logic ;
      MRESP_H         : OUT    std_logic ;
      Miss            : OUT    std_logic ;
      PMADDRESS       : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT L1WithWriteEvictControl
   PORT (
      Dirty       : IN     std_logic ;
      Miss        : IN     std_logic ;
      PMRESP_H    : IN     std_logic ;
      RESET_L     : IN     std_logic ;
      clk         : IN     std_logic ;
      InLoad      : OUT    std_logic ;
      InWaitHit   : OUT    std_logic ;
      InWriteBack : OUT    std_logic ;
      PMREAD_L    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : EvictionWriteBuffer USE ENTITY ece411.EvictionWriteBuffer;
   FOR ALL : L1WithWriteEvict USE ENTITY ece411.L1WithWriteEvict;
   FOR ALL : L1WithWriteEvictControl USE ENTITY ece411.L1WithWriteEvictControl;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   WriteBuffer : EvictionWriteBuffer
      PORT MAP (
         DataWriteMuxout => DataWriteMuxout,
         InWriteBack     => InWriteBack,
         PMRESP_H        => PMRESP_H,
         RESET_L         => RESET_L,
         clk             => clk,
         PMDATAOUT       => PMDATAOUT,
         PMWRITE_L       => PMWRITE_L
      );
   Cache_DP : L1WithWriteEvict
      PORT MAP (
         ADDRESS         => ADDRESS,
         DATAOUT         => DATAOUT,
         InLoad          => InLoad,
         InWaitHit       => InWaitHit,
         InWriteBack     => InWriteBack,
         MREAD_L         => MREAD_L,
         MWRITEH_L       => MWRITEH_L,
         MWRITEL_L       => MWRITEL_L,
         PMDATAIN        => PMDATAIN,
         RESET_L         => RESET_L,
         clk             => clk,
         DATAIN          => DATAIN,
         DataWriteMuxout => DataWriteMuxout,
         Dirty           => Dirty,
         MRESP_H         => MRESP_H,
         Miss            => Miss,
         PMADDRESS       => PMADDRESS
      );
   Cache_Control : L1WithWriteEvictControl
      PORT MAP (
         Dirty       => Dirty,
         Miss        => Miss,
         PMRESP_H    => PMRESP_H,
         RESET_L     => RESET_L,
         clk         => clk,
         InLoad      => InLoad,
         InWaitHit   => InWaitHit,
         InWriteBack => InWriteBack,
         PMREAD_L    => PMREAD_L
      );

END struct;
