-- VHDL Entity ece411.L2Cache.interface
--
-- Created:
--          by - chao16.ews (gelib-057-18.ews.illinois.edu)
--          at - 05:53:47 12/06/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY L2Cache IS
   PORT( 
      DATAIN     : IN     LC3B_OWORD;
      L2_ADDRESS : IN     LC3b_word;
      L2_DATAOUT : IN     LC3B_OWORD;
      L2_READ_L  : IN     std_logic;
      L2_WRITE_L : IN     std_logic;
      MRESP_H    : IN     std_logic;
      RESET_L    : IN     STD_LOGIC;
      clk        : IN     STD_LOGIC;
      ADDRESS    : OUT    LC3b_word;
      DATAOUT    : OUT    LC3B_OWORD;
      L2_DATAIN  : OUT    LC3B_OWORD;
      L2_RESP_H  : OUT    std_logic;
      MREAD_L    : OUT    std_logic;
      MWRITE_L   : OUT    std_logic
   );

-- Declarations

END L2Cache ;

--
-- VHDL Architecture ece411.L2Cache.struct
--
-- Created:
--          by - chao16.ews (gelib-057-18.ews.illinois.edu)
--          at - 05:53:48 12/06/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF L2Cache IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Dirty       : std_logic;
   SIGNAL InLoad      : std_logic;
   SIGNAL InWaitHit   : std_logic;
   SIGNAL InWriteBack : std_logic;
   SIGNAL Miss        : std_logic;


   -- Component Declarations
   COMPONENT L2_Cache_Controller
   PORT (
      Dirty       : IN     std_logic ;
      Miss        : IN     std_logic ;
      PMRESP_H    : IN     std_logic ;
      RESET_L     : IN     std_logic ;
      clk         : IN     std_logic ;
      InLoad      : OUT    std_logic ;
      InWaitHit   : OUT    std_logic ;
      InWriteBack : OUT    std_logic ;
      PMREAD_L    : OUT    std_logic ;
      PMWRITE_L   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT L2_Cache_Datapath
   PORT (
      ADDRESS     : IN     LC3b_word ;
      CLK         : IN     STD_LOGIC ;
      DATAOUT     : IN     LC3B_OWORD ;
      InLoad      : IN     std_logic ;
      InWaitHit   : IN     std_logic ;
      InWriteBack : IN     std_logic ;
      MREAD_L     : IN     std_logic ;
      MWRITEH_L   : IN     std_logic ;
      MWRITEL_L   : IN     std_logic ;
      PMDATAIN    : IN     LC3B_OWORD ;
      RESET_L     : IN     STD_LOGIC ;
      DATAIN      : OUT    LC3B_OWORD ;
      Dirty       : OUT    std_logic ;
      MRESP_H     : OUT    std_logic ;
      Miss        : OUT    std_logic ;
      PMADDRESS   : OUT    LC3b_word ;
      PMDATAOUT   : OUT    LC3B_OWORD 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : L2_Cache_Controller USE ENTITY ece411.L2_Cache_Controller;
   FOR ALL : L2_Cache_Datapath USE ENTITY ece411.L2_Cache_Datapath;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   Cache_Control : L2_Cache_Controller
      PORT MAP (
         Dirty       => Dirty,
         Miss        => Miss,
         PMRESP_H    => MRESP_H,
         RESET_L     => RESET_L,
         clk         => clk,
         InLoad      => InLoad,
         InWaitHit   => InWaitHit,
         InWriteBack => InWriteBack,
         PMREAD_L    => MREAD_L,
         PMWRITE_L   => MWRITE_L
      );
   L2_Cache_DP : L2_Cache_Datapath
      PORT MAP (
         ADDRESS     => L2_ADDRESS,
         CLK         => clk,
         DATAOUT     => L2_DATAOUT,
         InLoad      => InLoad,
         InWaitHit   => InWaitHit,
         InWriteBack => InWriteBack,
         MREAD_L     => L2_READ_L,
         MWRITEH_L   => L2_WRITE_L,
         MWRITEL_L   => L2_WRITE_L,
         PMDATAIN    => DATAIN,
         RESET_L     => RESET_L,
         DATAIN      => L2_DATAIN,
         Dirty       => Dirty,
         MRESP_H     => L2_RESP_H,
         Miss        => Miss,
         PMADDRESS   => ADDRESS,
         PMDATAOUT   => DATAOUT
      );

END struct;
