-- VHDL Entity ece411.orUCBR.generatedInstance
--
-- Created:
--          by - li151.ews (evrt-252-05.ews.illinois.edu)
--          at - 09:10:06 12/07/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY orUCBR IS
   PORT( 
      BrMuxSel    : IN     STD_LOGIC;
      clk         : IN     std_logic;
      IF_Opcodein : IN     LC3b_Opcode;
      UCBrSel     : OUT    std_logic
   );

END orUCBR ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF orUCBR IS 
BEGIN


END generatedInstance;
