-- VHDL Entity ece411.ShiftUnit.generatedInstance
--
-- Created:
--          by - schen79.ews (linux-a1.ews.illinois.edu)
--          at - 20:04:37 09/11/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ShiftUnit IS
   PORT( 
      ALUop  : IN     LC3b_aluop;
      ALUout : OUT    LC3b_word;
      clk    : IN     std_logic;
      index6 : IN     LC3b_index6;
      RFAout : IN     LC3b_word
   );

END ShiftUnit ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ShiftUnit IS 
BEGIN


END generatedInstance;
