-- VHDL Entity ece411.Stage_Memory.interface
--
-- Created:
--          by - schen79.ews (linux-a1.ews.illinois.edu)
--          at - 21:46:10 10/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY Stage_Memory IS
   PORT( 
      DATAIN        : IN     LC3b_word;
      LoadMAR       : IN     std_logic;
      LoadMDR       : IN     std_logic;
      MARMuxsel     : IN     LC3b_4mux_sel;
      MDRMuxsel     : IN     LC3b_4mux_sel;
      MEM_ALUout    : IN     LC3b_word;
      MEM_PCPlus2   : IN     LC3b_word;
      MEM_TRAPVECT8 : IN     LC3b_word;
      RESET_L       : IN     std_logic;
      clk           : IN     std_logic;
      MEM_MARout    : OUT    LC3b_word;
      MEM_MDRout    : OUT    LC3b_word
   );

-- Declarations

END Stage_Memory ;

--
-- VHDL Architecture ece411.Stage_Memory.struct
--
-- Created:
--          by - schen79.ews (linux-a1.ews.illinois.edu)
--          at - 21:46:10 10/19/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF Stage_Memory IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL MARMuxout   : LC3b_word;
   SIGNAL MDRMuxout   : LC3b_word;
   SIGNAL SelHByteout : LC3b_word;
   SIGNAL SelLByteout : LC3b_word;

   -- Implicit buffer signal declarations
   SIGNAL MEM_MDRout_internal : LC3b_word;


   -- Component Declarations
   COMPONENT Reg16
   PORT (
      Input  : IN     LC3b_word ;
      RESET  : IN     std_logic ;
      clk    : IN     std_logic ;
      load   : IN     std_logic ;
      Output : OUT    LC3b_word 
   );
   END COMPONENT;
   COMPONENT SelHByte
   PORT (
      A           : IN     LC3b_word;
      SelHByteout : OUT    LC3b_word
   );
   END COMPONENT;
   COMPONENT SelLByte
   PORT (
      A           : IN     LC3b_word;
      SelLByteout : OUT    LC3b_word
   );
   END COMPONENT;
   COMPONENT WordMux4
   PORT (
      A   : IN     LC3b_word ;
      B   : IN     LC3b_word ;
      C   : IN     LC3b_word ;
      D   : IN     LC3b_word ;
      Sel : IN     LC3b_4mux_sel ;
      F   : OUT    LC3b_word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Reg16 USE ENTITY ece411.Reg16;
   FOR ALL : SelHByte USE ENTITY ece411.SelHByte;
   FOR ALL : SelLByte USE ENTITY ece411.SelLByte;
   FOR ALL : WordMux4 USE ENTITY ece411.WordMux4;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   MAR : Reg16
      PORT MAP (
         Input  => MARMuxout,
         RESET  => RESET_L,
         clk    => clk,
         load   => LoadMAR,
         Output => MEM_MARout
      );
   MDR : Reg16
      PORT MAP (
         Input  => MDRMuxout,
         RESET  => RESET_L,
         clk    => clk,
         load   => LoadMDR,
         Output => MEM_MDRout_internal
      );
   aSelHByte : SelHByte
      PORT MAP (
         A           => MEM_ALUout,
         SelHByteout => SelHByteout
      );
   aSelLByte : SelLByte
      PORT MAP (
         A           => MEM_ALUout,
         SelLByteout => SelLByteout
      );
   MARMux : WordMux4
      PORT MAP (
         A   => MEM_PCPlus2,
         B   => MEM_ALUout,
         C   => MEM_MDRout_internal,
         D   => MEM_TRAPVECT8,
         Sel => MARMuxsel,
         F   => MARMuxout
      );
   MDRMux : WordMux4
      PORT MAP (
         A   => DATAIN,
         B   => SelHByteout,
         C   => SelLByteout,
         D   => MEM_ALUout,
         Sel => MDRMuxsel,
         F   => MDRMuxout
      );

   -- Implicit buffered output assignments
   MEM_MDRout <= MEM_MDRout_internal;

END struct;
