-- VHDL Entity ece411.u2bitmux.generatedInstance
--
-- Created:
--          by - chao16.ews (gelib-057-17.ews.illinois.edu)
--          at - 16:39:39 12/05/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY u2bitmux IS
   PORT( 
      BRMuxSel     : IN     STD_LOGIC;
      clk          : IN     std_logic;
      IsBR         : IN     STD_LOGIC;
      MEM_OPCODE   : IN     LC3b_OPCODE;
      PCMuxSel     : IN     LC3b_4mux_sel;
      PCMuxSel_out : OUT    LC3b_4mux_sel;
      PCMuxSel_Wr  : IN     LC3b_4MUX_SEL;
      TakeBR       : IN     std_logic
   );

END u2bitmux ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF u2bitmux IS 
BEGIN


END generatedInstance;
